/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bibliotheque;

import entities.Adherant;
import static javafx.scene.input.KeyCode.T;
import javax.swing.JOptionPane;
import javax.ws.rs.client.Client;
import javax.ws.rs.client.ClientBuilder;
import javax.ws.rs.client.Entity;
import javax.ws.rs.client.WebTarget;
import javax.ws.rs.core.Form;
import javax.ws.rs.core.MediaType;
import javax.ws.rs.core.Response;
import org.glassfish.jersey.client.ClientConfig;

/**
 *
 * @author juba
 */
public class ModifierAdherant extends javax.swing.JFrame {

    /**
     * Creates new form ModifierAdherant
     */
    private final GestionAdherant gestionAdh;

    public ModifierAdherant(GestionAdherant gestionAdh) {
        initComponents();
        this.gestionAdh = gestionAdh;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        TFNumAdh = new javax.swing.JTextField();
        TFNomAdh = new javax.swing.JTextField();
        TFPrenomAdh = new javax.swing.JTextField();
        TFAdresseAdh = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        validerModification = new javax.swing.JButton();
        recherche = new javax.swing.JButton();

        setResizable(false);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                formComponentHidden(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("Modifier adhérant");

        TFNumAdh.setName("TFNumAdh"); // NOI18N

        TFNomAdh.setName("TFNomAdh"); // NOI18N

        TFPrenomAdh.setName("TFPrenomAdh"); // NOI18N

        TFAdresseAdh.setName("TFAdresseAdh"); // NOI18N

        jLabel5.setText("Adresse");

        jLabel4.setText("Prénom");

        jLabel3.setText("Nom");

        jLabel2.setText("Numéro adhérant");

        validerModification.setText("Valider la modification");
        validerModification.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                validerModificationActionPerformed(evt);
            }
        });

        recherche.setText("Rcherche");
        recherche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rechercheActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(TFNumAdh, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(recherche, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(TFNomAdh)
                            .addComponent(TFPrenomAdh)
                            .addComponent(TFAdresseAdh))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 126, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(validerModification, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(102, 102, 102))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(120, 120, 120))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TFNumAdh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(recherche))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TFNomAdh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(TFPrenomAdh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(TFAdresseAdh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(validerModification)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void validerModificationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_validerModificationActionPerformed
        JOptionPane jop = new JOptionPane();
        int option = jop.showConfirmDialog(this,
                "êtes vous sur de vouloir modifier cet élément?",
                "Modification",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE);

        if (option == JOptionPane.OK_OPTION) {
            String rep = gestionAdh.ModifierAdherant(TFNumAdh.getText(), TFNomAdh.getText(), TFPrenomAdh.getText(), TFAdresseAdh.getText());
            if ("erreur".equals(rep)) {
                JOptionPane.showMessageDialog(null, "Erreur", "Erreur", JOptionPane.ERROR_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(null, "Modification réussie", "Modification", JOptionPane.INFORMATION_MESSAGE);
                resetForm();
            }
        }

    }//GEN-LAST:event_validerModificationActionPerformed
    private void resetForm(){
        TFNomAdh.setText("");
        TFPrenomAdh.setText("");
        TFAdresseAdh.setText("");
    }
    private void rechercheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rechercheActionPerformed

        try {
            Adherant adh = gestionAdh.getAdherantById(TFNumAdh.getText());
            if (adh.getNumAdh() == null) {
                JOptionPane.showMessageDialog(null, "Aucun élément trouvé", "Modification", JOptionPane.INFORMATION_MESSAGE);
            } else {
                TFNomAdh.setText(adh.getNomAdh());
                TFPrenomAdh.setText(adh.getPrenomAdh());
                TFAdresseAdh.setText(adh.getAdresseAdh());
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erreur", "Modification", JOptionPane.ERROR_MESSAGE);

        }
    }//GEN-LAST:event_rechercheActionPerformed

    private void formComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentHidden
        TFNumAdh.setText("");
        resetForm();
    }//GEN-LAST:event_formComponentHidden

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TFAdresseAdh;
    private javax.swing.JTextField TFNomAdh;
    private javax.swing.JTextField TFNumAdh;
    private javax.swing.JTextField TFPrenomAdh;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JButton recherche;
    private javax.swing.JButton validerModification;
    // End of variables declaration//GEN-END:variables
}
