/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bibliotheque;

import entities.Adherant;
import javax.swing.JOptionPane;

/**
 *
 * @author juba
 */
public class SupprimerAdherant extends javax.swing.JFrame {

    /**
     * Creates new form SupprimerAdherant
     */
    private final GestionAdherant gestionAdh;

    public SupprimerAdherant(GestionAdherant gestionAdh) {
        initComponents();
        this.gestionAdh = gestionAdh;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TFNumAdh = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        BTRecherche = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        resultatRche = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        LNomAdh = new javax.swing.JLabel();
        LPrenomAdh = new javax.swing.JLabel();
        LAdresseAdh = new javax.swing.JLabel();
        numResult = new javax.swing.JLabel();
        supprimer = new javax.swing.JButton();

        setResizable(false);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                formComponentHidden(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setText("Supprimer adhérant");

        BTRecherche.setText("Recherche");
        BTRecherche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTRechercheActionPerformed(evt);
            }
        });

        jLabel1.setText("Numéro adhérant");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setText("Nom");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setText("Prénom");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel8.setText("Adresse");

        LNomAdh.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        LNomAdh.setText("_");

        LPrenomAdh.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        LPrenomAdh.setText("_");

        LAdresseAdh.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        LAdresseAdh.setText("_");

        javax.swing.GroupLayout resultatRcheLayout = new javax.swing.GroupLayout(resultatRche);
        resultatRche.setLayout(resultatRcheLayout);
        resultatRcheLayout.setHorizontalGroup(
            resultatRcheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(resultatRcheLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(resultatRcheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addGap(36, 36, 36)
                .addGroup(resultatRcheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LAdresseAdh)
                    .addComponent(LPrenomAdh)
                    .addComponent(LNomAdh))
                .addContainerGap(173, Short.MAX_VALUE))
        );
        resultatRcheLayout.setVerticalGroup(
            resultatRcheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(resultatRcheLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(resultatRcheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(LNomAdh))
                .addGap(18, 18, 18)
                .addGroup(resultatRcheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(LPrenomAdh))
                .addGap(18, 18, 18)
                .addGroup(resultatRcheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(LAdresseAdh))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        numResult.setVisible(false);
        numResult.setText("aucun élément trouvé");

        supprimer.setText("Supprimer");
        supprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supprimerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(TFNumAdh, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(20, 20, 20)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BTRecherche)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(resultatRche, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(numResult)
                        .addGap(156, 156, 156))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(supprimer, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TFNumAdh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(BTRecherche))
                .addGap(18, 18, 18)
                .addComponent(numResult)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(resultatRche, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(supprimer)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTRechercheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTRechercheActionPerformed

        try {
            Adherant adh = gestionAdh.getAdherantById(TFNumAdh.getText());
            if (adh.getNumAdh() == null) {
                JOptionPane.showMessageDialog(null, "Aucun élément trouvé", "Suppréssion", JOptionPane.INFORMATION_MESSAGE);
            } else {
                LNomAdh.setText(adh.getNomAdh());
                LPrenomAdh.setText(adh.getPrenomAdh());
                LAdresseAdh.setText(adh.getAdresseAdh());
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erreur", "Suppréssion", JOptionPane.ERROR_MESSAGE);

        }
    }//GEN-LAST:event_BTRechercheActionPerformed
    private void resetForm() {
        
        LNomAdh.setText("_");
        LPrenomAdh.setText("_");
        LAdresseAdh.setText("_");
    }
    private void supprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supprimerActionPerformed
        JOptionPane jop = new JOptionPane();
        int option = jop.showConfirmDialog(this,
                "êtes vous sur de vouloir supprimer cet élément?",
                "Suppréssion",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE);

        if (option == JOptionPane.OK_OPTION) {
            gestionAdh.SuppAdherantById(TFNumAdh.getText());
           resetForm();
        }
    }//GEN-LAST:event_supprimerActionPerformed

    private void formComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentHidden
        TFNumAdh.setText("");
        resetForm();
    }//GEN-LAST:event_formComponentHidden

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTRecherche;
    private javax.swing.JLabel LAdresseAdh;
    private javax.swing.JLabel LNomAdh;
    private javax.swing.JLabel LPrenomAdh;
    private javax.swing.JTextField TFNumAdh;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel numResult;
    private javax.swing.JPanel resultatRche;
    private javax.swing.JButton supprimer;
    // End of variables declaration//GEN-END:variables
}
